### ISSUE TITLE
仿真环境运行demo失败，代码bug

### ISSUE THREAD

**Issue by yimengweima0** [chenhanpolyu/AutoFly-demo#1]
你好，我已经根据你的仿真环境_demo配置好，进行代码编译并没有报错，整个框架如图所示
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/cb2c91c8-56c1-4354-9726-44b29adc5665)，同时我也发现你的gazebo_playground中的子模块下载不了的
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/88c4b5ba-051d-489d-9f19-80a9138381e2)，如下我运行你的仿真demo，四个launch文件，输出窗口如下
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/05a07a8a-083d-40e7-9f49-03d068052a46)
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/5b7bc20b-9f76-4067-b732-739213da1471)
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/dbf005b1-83ae-4771-ba78-0e7a89cec8c6)
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/3f899326-84fd-466b-bb10-bc362a8cd4fc)
gazebo和rviz显示如下，无人机是不移动的，同时相机的点云话题是没有数据发布
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/3e6a240c-aba0-4398-9269-6f384f6b664e)
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/b81fb4ab-e1b0-43b5-9964-5d022532bc49)
，整个demo是不能跑的，无人机静止

**Comment by yimengweima0** [comment]
你好，可以给帮忙解答一下吗 @chenhanpolyu

**Comment by yimengweima0** [comment]
我觉得最主要的原因是因为点云话题没有发布数据，所以roslaunch yolodetector sim_yolo_ros.launch 没法进行后面piv流程，后面无法进行运动规划，所以还是d435点云没有发布的问题，你能帮忙给解决下吗

**Comment by chenhanpolyu** [comment]
应该是默认的launch文件里ros消息的remap需要修改一下。障碍物感知模块需要三个消息：“/filtered_RadiusOutlierRemoval” "/mavros/imu/data" "/vicon_imu_ekf_odom"。如果这三个消息都存在应该可以在rviz里看到行人的位置速度估计结果。如果是最后一个odom消息不存在可以检查是否有其他的无人机odom消息发布，利用remap映射一下。可以参考src/yolo_fdsst_piv/dyn_object_tracker/launch/piv_filter_start_sim.launch 里22行的注释，注意remap要放到node标签内。如果这里修改了remap那src/UAPE_planner/launch/sim_traj_node.launch里也要对应修改。

**Comment by chenhanpolyu** [comment]
如果"/camera/depth/color/points"这个消息没有发布那就是gazebo的相机插件出问题了，但是看你的截图里已经有深度图了，应该不是这个问题。请用rostopic echo /camera/depth/color/points 检查，rviz里默认显示世界坐标系，看不到camera坐标系的点云的

**Comment by shenyuan411** [comment]
您好！
请问代码跑通了吗？ @yimengweima0

**Comment by yimengweima0** [comment]
> 您好！ 请问代码跑通了吗？ @yimengweima0

没有呢，我今天才改了下，还是不行

**Comment by yimengweima0** [comment]
> 应该是默认的launch文件里ros消息的remap需要修改一下。障碍物感知模块需要三个消息：“/filtered_RadiusOutlierRemoval” "/mavros/imu/data" "/vicon_imu_ekf_odom"。如果这三个消息都存在应该可以在rviz里看到行人的位置速度估计结果。如果是最后一个odom消息不存在可以检查是否有其他的无人机odom消息发布，利用remap映射一下。可以参考src/yolo_fdsst_piv/dyn_object_tracker/launch/piv_filter_start_sim.launch 里22行的注释，注意remap要放到node标签内。如果这里修改了remap那src/UAPE_planner/launch/sim_traj_node.launch里也要对应修改。

你好，我已经按照你所说的改了，rviz可以看到了显示的行人了，我是将         <remap from="/vicon_imu_ekf_odom"  to="/gt_iris_base_link_imu"/>，rviz如图所示

![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/63dc9c9f-87de-4d4e-b3a0-3b3b3ab6aa8f)
但是无人机还是不移动，src/UAPE_planner/launch/sim_traj_node.launch我改为如下了，yaml文件没动
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/dfd57f22-905e-45a6-a029-80a96f21b87b)
终端输出四个launch文件如下
![image](https://github.com/chenhanpolyu/AutoFly-demo/assets/50518889/9570b0aa-0a2e-4b76-bba0-9ec9ff9cf57a)
你好，能麻烦你再解答一下吗，我是刚开始学规划，这个无人机还不是很懂，只是把tmac那篇论文看懂了

**Comment by shenyuan411** [comment]
> > 您好！ 请问代码跑通了吗？ @yimengweima0
> 
> 没有呢，我今天才改了下，还是不行

你好，我今天刚跑通

**Comment by shenyuan411** [comment]
> > 应该是默认的launch文件里ros消息的remap需要修改一下。障碍物感知模块需要三个消息：“/filtered_RadiusOutlierRemoval” "/mavros/imu/data" "/vicon_imu_ekf_odom"。如果这三个消息都存在应该可以在rviz里看到行人的位置速度估计结果。如果是最后一个odom消息不存在可以检查是否有其他的无人机odom消息发布，利用remap映射一下。可以参考src/yolo_fdsst_piv/dyn_object_tracker/launch/piv_filter_start_sim.launch 里22行的注释，注意remap要放到node标签内。如果这里修改了remap那src/UAPE_planner/launch/sim_traj_node.launch里也要对应修改。
> 
> 你好，我已经按照你所说的改了，rviz可以看到了显示的行人了，我是将 ，rviz如图所示
> 
> ![image](https://private-user-images.githubusercontent.com/50518889/329479799-63dc9c9f-87de-4d4e-b3a0-3b3b3ab6aa8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0Nzk3OTktNjNkYzljOWYtODdkZS00ZDRlLWIzYTAtM2IzYjNhYjZhYThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYjEwMTIxYzU1YWUxZjNiNTIxOWY1N2QyMmZkNWQ0NjZlOWRlYTg2MjljNTRiNmJkMTc5MTNhODY1NWQ4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4IuoJuHKkO7o3P20p2yv3bMBVf2QjkQxMcqDkfMH0k) 但是无人机还是不移动，src/UAPE_planner/launch/sim_traj_node.launch我改为如下了，yaml文件没动 ![image](https://private-user-images.githubusercontent.com/50518889/329480108-dfd57f22-905e-45a6-a029-80a96f21b87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0ODAxMDgtZGZkNTdmMjItOTA1ZS00NWE2LWEwMjktODBhOTZmMjFiODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NWRiYzc1OGE2NmE4MjdkYjIyMjU3YjZhODkxMmIwMzg5YTY2NzgyYzc3OWIzNmMwMzM4NTg5NjhhNWZiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yxKh1M4eJkFm4IoISKvUAnDVtD03bWCEyM6DfX_j-T0) 终端输出四个launch文件如下 ![image](https://private-user-images.githubusercontent.com/50518889/329480331-9570b0aa-0a2e-4b76-bba0-9ec9ff9cf57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0ODAzMzEtOTU3MGIwYWEtMGEyZS00Yjc2LWJiYTAtOWVjOWZmOWNmNTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZGY1NGNkZTk3OGQxODcwYWFjYmY5MjAwOTU3NTNlOTZiNzFjNWUwYzA2MTM3NmEzMDE4OTFlNWY2N2U0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTaSKG_RpIlELNCkmlXQTaBaRass0gFu6M3LFNE170I) 你好，能麻烦你再解答一下吗，我是刚开始学规划，这个无人机还不是很懂，只是把tmac那篇论文看懂了

感觉你需要把地面站的虚拟摇杆打开。第一个终端里面PX4没有起飞，感觉需要看下那个WARN。其他终端貌似和我的一致

**Comment by yimengweima0** [comment]
> > > 应该是默认的launch文件里ros消息的remap需要修改一下。障碍物感知模块需要三个消息：“/filtered_RadiusOutlierRemoval” "/mavros/imu/data" "/vicon_imu_ekf_odom"。如果这三个消息都存在应该可以在rviz里看到行人的位置速度估计结果。如果是最后一个odom消息不存在可以检查是否有其他的无人机odom消息发布，利用remap映射一下。可以参考src/yolo_fdsst_piv/dyn_object_tracker/launch/piv_filter_start_sim.launch 里22行的注释，注意remap要放到node标签内。如果这里修改了remap那src/UAPE_planner/launch/sim_traj_node.launch里也要对应修改。
> > 
> > 
> > 你好，我已经按照你所说的改了，rviz可以看到了显示的行人了，我是将 ，rviz如图所示
> > ![image](https://private-user-images.githubusercontent.com/50518889/329479799-63dc9c9f-87de-4d4e-b3a0-3b3b3ab6aa8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0Nzk3OTktNjNkYzljOWYtODdkZS00ZDRlLWIzYTAtM2IzYjNhYjZhYThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYjEwMTIxYzU1YWUxZjNiNTIxOWY1N2QyMmZkNWQ0NjZlOWRlYTg2MjljNTRiNmJkMTc5MTNhODY1NWQ4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4IuoJuHKkO7o3P20p2yv3bMBVf2QjkQxMcqDkfMH0k) 但是无人机还是不移动，src/UAPE_planner/launch/sim_traj_node.launch我改为如下了，yaml文件没动 ![image](https://private-user-images.githubusercontent.com/50518889/329480108-dfd57f22-905e-45a6-a029-80a96f21b87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0ODAxMDgtZGZkNTdmMjItOTA1ZS00NWE2LWEwMjktODBhOTZmMjFiODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NWRiYzc1OGE2NmE4MjdkYjIyMjU3YjZhODkxMmIwMzg5YTY2NzgyYzc3OWIzNmMwMzM4NTg5NjhhNWZiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yxKh1M4eJkFm4IoISKvUAnDVtD03bWCEyM6DfX_j-T0) 终端输出四个launch文件如下 ![image](https://private-user-images.githubusercontent.com/50518889/329480331-9570b0aa-0a2e-4b76-bba0-9ec9ff9cf57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE5NjIsIm5iZiI6MTcxNTMzMTY2MiwicGF0aCI6Ii81MDUxODg4OS8zMjk0ODAzMzEtOTU3MGIwYWEtMGEyZS00Yjc2LWJiYTAtOWVjOWZmOWNmNTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA5MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZGY1NGNkZTk3OGQxODcwYWFjYmY5MjAwOTU3NTNlOTZiNzFjNWUwYzA2MTM3NmEzMDE4OTFlNWY2N2U0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTaSKG_RpIlELNCkmlXQTaBaRass0gFu6M3LFNE170I) 你好，能麻烦你再解答一下吗，我是刚开始学规划，这个无人机还不是很懂，只是把tmac那篇论文看懂了
> 
> 感觉你需要把地面站的虚拟摇杆打开。第一个终端里面PX4没有起飞，感觉需要看下那个WARN。其他终端貌似和我的一致

好的，谢谢啊，那我安一下地面站，我是搞地面移动机器人的，不知道要安装地面站，本来是想来借鉴一下代码看看

**Comment by yimengweima0** [comment]
安装好Qground就跑通了
